# Generated by Django 5.0.1 on 2024-02-04 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("montessori_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="user",
        ),
    ]
