# Generated by Django 5.0.1 on 2024-02-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("montessori_app", "0002_remove_teacher_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="username",
            field=models.CharField(default=11, max_length=20),
            preserve_default=False,
        ),
    ]
