# Generated by Django 5.0.1 on 2024-02-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("montessori_app", "0004_remove_student_user_alter_mark_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
